hhru/frontik

frontik/handler.py, frontik/http_client.py, frontik/util.py, tests/projects/test_app/pages/head_url.py, tests/test_handler.py
https://jira.hh.ru/browse/HH-51329
=> HH-51329 add head_url for PageHandler

frontik/micro_handler.py, tests/projects/test_app/pages/micro_handler.py
https://jira.hh.ru/browse/HH-54606
=> HH-54606 Unicode uri in microhandler

tests/instances.py
[https://jira.hh.ru/browse/HH-53444](https://jira.hh.ru/browse/HH-53444)
=> HH-53444 fix coverage

frontik/frontik_logging.py
https://jira.hh.ru/browse/HH-55342
=> HH-55342 add frontik resource id to backend response log message

frontik/app.py, tests/test_routing.py
https://jira.hh.ru/browse/HH-56064
=> HH-56064 fix bug caused by "." char in url

frontik/server/__init__.py, setup.py, tests/projects/test_app/pages/cdata.py, tests/projects/test_app/pages/simple_xml.py, tests/test_jobs.py, tests/test_non_debug_mode.py, tests/test_routing.py, tests/test_xml_producer.py
and fix setup.py and python-daemon for tests
=> HH-57384 fix tests with str.find

frontik/handler_debug.py
https://jira.hh.ru/browse/HH-59444
Во фронтике научиться работать с сырыми протобуф объектами
=> HH-59444 make frontik able to use raw protobuf data

debian/control
В прошлом релизе забыл исправить зависимость
=> HH-59866 Fix depends

frontik/debug/debug-js.xsl
https://jira.hh.ru/browse/HH-57034
Не преобразуем `&quot;` в `"`.
=> HH-57034 fix unencoded characters issue

frontik/app.py, frontik/server/__init__.py
https://jira.hh.ru/browse/HH-60358
=> HH-60358 Start frontik application asynchronously

frontik/testing/service_mock.py
https://jira.hh.ru/browse/HH-60796
=> HH-60796 add application_kwargs to testing environment

frontik/http_client.py
https://jira.hh.ru/browse/HH-61746
=> HH-61746 move prohibition of keep-alive to backends from tornado

.travis.yml, setup.py, tests/test_http_client_keep_alive.py
https://jira.hh.ru/browse/HH-62024
=> HH-62024 fix CI

frontik/handler.py
https://jira.hh.ru/browse/HH-62067
=> HH-62067 add request id response header

frontik/handler.py, frontik/http_client.py, frontik/micro_handler.py, tests/projects/test_app/pages/micro_handler.py, tests/test_micro_handler.py
https://jira.hh.ru/browse/HH-63288
=> HH-63288 добавить в microhandler возможность принимать готовую Future

frontik/app.py, frontik/handler_debug.py, frontik/loggers/request.py, frontik/loggers/sentry.py, frontik/util.py, frontik/version.py, setup.py
https://jira.hh.ru/browse/HH-65293
=> fix pycodestyle issues

frontik/debug/debug.xsl, frontik/handler.py, frontik/handler_debug.py
https://jira.hh.ru/browse/HH-64560
Добавлено отображение кук в response headers разделе debug страницы
=> HH-64560 show cookies in response headers block of debug page

frontik/producers/json_producer.py
https://jira.hh.ru/browse/HH-74434
=> HH-74434 allow partial jinja templating

frontik/producers/json_producer.py
https://jira.hh.ru/browse/HH-74457
=> HH-74457 make pretty exceptions handling for stream-templating

frontik/producers/json_producer.py
https://jira.hh.ru/browse/HH-74483
=> HH-74483 allow to set rendering timeout

frontik/handler.py, frontik/validator.py, requirements.txt, tests/projects/test_app/pages/validate_arguments.py, tests/test_arguments.py
Добавляем возможность получения типизированных/отвалидированных аргументов
=> HH-124497 add getting typed arguments
